### PR TITLE
Contact Form Styling Fix

### PR DESCRIPTION
**Pull request by queenofthelosers**
I fixed the styling issues.
About the email notifications, I deployed it myself on Netlify to test and it seems to work. Has Step 8 from [here](https://www.freecodecamp.org/news/how-to-add-a-netlify-form-to-a-react-app/) been done? Please make sure that the form submissions are legitimate while testing, as Netlify has spam filtering built in.

### CODE REVIEW

**Comment by queenofthelosers** [comment]
@huntzinger92 could you check it out?

**Comment by huntzinger92** [comment]
Just had time to test it again. I didn't receive an email, but it may be something on my end, in terms of how Netlify is configured. I'm going to double check that that is all good.

In the meantime, if you have time, I'd really like the text in the inputs to be left-top aligned rather than vertically centered. If you don't get to it, I'll take care of it before merging.

**Comment by huntzinger92** [comment]
Turns out the issue was on my end, sorry about that. It works! Thanks for doing this.

Two last styling things and I'd love before merging this. At screen widths of <1000px, the contact page gets super wide. The subject text is also vertically aligned in a box that's pretty tall.

I've attached screenshots showing how to change the css. I'd push it up myself, but I think this is a commit on the master branch and not a separate branch. Mind making this adjustments when you get a chance?

Great work on everything else, thanks, much appreciated.

Screen Shot 2021-11-04 at 11 37 19 AM
Screen Shot 2021-11-04 at 11 35 47 AM

**Comment by huntzinger92** [comment]
I'm just going to go ahead and merge this, will take care of those minor styling issues.

**Comment by queenofthelosers** [comment]
Thanks! Sorry I didn't see this earlier, would've done these myself

**Pull request merged**
